### ISSUE TITLE
Aimesh node

### ISSUE THREAD

**Issue by maghuro** [maverickcdn/wicens#6]
I'd like to install your script on an aimesh node (no USB, no entware), just to have the function to receive email when firmware update is available.
However, it's impossible to install because getrealip.sh doesn't retrieve an IP address.
Is it possible to install it just to have the firmware email option?

**Comment by maverickcdn** [comment]
Hey maghuro

Im working on V4 which will have this ability but currently have lost the motivation to continue this project.  V4 is only roughly 40%-50% complete.  We'll see if I can get around to picking up where I left off.   Ill let you know if and when a beta is ready to test out.   It seems ministun package is disabled when in aimesh mode, maybe you can find a way to re-enable it? https://www.snbforums.com/threads/what-is-the-ministun-program.37725/

**Comment by maghuro** [comment]
My friend,

Tell me what's the motif of your lack of motivation on this project.

I'm here to help, learning bash on the free hours ☺️

**Comment by maverickcdn** [comment]
The script is so large that putting it down for any length of time requires investing lots more time re-acquainting myself with its function just to pick up where I left off.  This combined with learning new techniques/formatting requires making numerous re-writes of large portions of the script which just adds time (and frustration)

I have 100's of hours into V1,V2,V3 and because its a hobby project I've just been reinvesting my time/energy into other things.  Its only roughly 4000 lines so kudos to those that maintain even larger scripts

**Comment by maverickcdn** [comment]
v4.00 is available :)
